# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_demo_pb2 as grpc__demo__pb2


class RouteDemoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
                '/grpcdemo.RouteDemo/GetItem',
                request_serializer=grpc__demo__pb2.ItemId.SerializeToString,
                response_deserializer=grpc__demo__pb2.Item.FromString,
                )
        self.ListItems = channel.unary_unary(
                '/grpcdemo.RouteDemo/ListItems',
                request_serializer=grpc__demo__pb2.ListItemsPagination.SerializeToString,
                response_deserializer=grpc__demo__pb2.ListItemsSchema.FromString,
                )
        self.CreateItem = channel.unary_unary(
                '/grpcdemo.RouteDemo/CreateItem',
                request_serializer=grpc__demo__pb2.CreateItemSchema.SerializeToString,
                response_deserializer=grpc__demo__pb2.Item.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/grpcdemo.RouteDemo/UpdateItem',
                request_serializer=grpc__demo__pb2.UpdateItemSchema.SerializeToString,
                response_deserializer=grpc__demo__pb2.Item.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/grpcdemo.RouteDemo/DeleteItem',
                request_serializer=grpc__demo__pb2.ItemId.SerializeToString,
                response_deserializer=grpc__demo__pb2.Empty.FromString,
                )


class RouteDemoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=grpc__demo__pb2.ItemId.FromString,
                    response_serializer=grpc__demo__pb2.Item.SerializeToString,
            ),
            'ListItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=grpc__demo__pb2.ListItemsPagination.FromString,
                    response_serializer=grpc__demo__pb2.ListItemsSchema.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=grpc__demo__pb2.CreateItemSchema.FromString,
                    response_serializer=grpc__demo__pb2.Item.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=grpc__demo__pb2.UpdateItemSchema.FromString,
                    response_serializer=grpc__demo__pb2.Item.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=grpc__demo__pb2.ItemId.FromString,
                    response_serializer=grpc__demo__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcdemo.RouteDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteDemo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcdemo.RouteDemo/GetItem',
            grpc__demo__pb2.ItemId.SerializeToString,
            grpc__demo__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcdemo.RouteDemo/ListItems',
            grpc__demo__pb2.ListItemsPagination.SerializeToString,
            grpc__demo__pb2.ListItemsSchema.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcdemo.RouteDemo/CreateItem',
            grpc__demo__pb2.CreateItemSchema.SerializeToString,
            grpc__demo__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcdemo.RouteDemo/UpdateItem',
            grpc__demo__pb2.UpdateItemSchema.SerializeToString,
            grpc__demo__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcdemo.RouteDemo/DeleteItem',
            grpc__demo__pb2.ItemId.SerializeToString,
            grpc__demo__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
