# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_demo.proto\x12\x08grpcdemo\"\x07\n\x05\x45mpty\"!\n\x10\x43reateItemSchema\x12\r\n\x05title\x18\x01 \x01(\t\"-\n\x10UpdateItemSchema\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"\x14\n\x06ItemId\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x13ListItemsPagination\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x13\n\x0bpage_length\x18\x02 \x01(\x05\"0\n\x0fListItemsSchema\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.grpcdemo.Item\"5\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t2\xa4\x02\n\tRouteDemo\x12+\n\x07GetItem\x12\x10.grpcdemo.ItemId\x1a\x0e.grpcdemo.Item\x12\x45\n\tListItems\x12\x1d.grpcdemo.ListItemsPagination\x1a\x19.grpcdemo.ListItemsSchema\x12\x38\n\nCreateItem\x12\x1a.grpcdemo.CreateItemSchema\x1a\x0e.grpcdemo.Item\x12\x38\n\nUpdateItem\x12\x1a.grpcdemo.UpdateItemSchema\x1a\x0e.grpcdemo.Item\x12/\n\nDeleteItem\x12\x10.grpcdemo.ItemId\x1a\x0f.grpcdemo.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=29
  _EMPTY._serialized_end=36
  _CREATEITEMSCHEMA._serialized_start=38
  _CREATEITEMSCHEMA._serialized_end=71
  _UPDATEITEMSCHEMA._serialized_start=73
  _UPDATEITEMSCHEMA._serialized_end=118
  _ITEMID._serialized_start=120
  _ITEMID._serialized_end=140
  _LISTITEMSPAGINATION._serialized_start=142
  _LISTITEMSPAGINATION._serialized_end=198
  _LISTITEMSSCHEMA._serialized_start=200
  _LISTITEMSSCHEMA._serialized_end=248
  _ITEM._serialized_start=250
  _ITEM._serialized_end=303
  _ROUTEDEMO._serialized_start=306
  _ROUTEDEMO._serialized_end=598
# @@protoc_insertion_point(module_scope)
